# Generated by Django 5.0.6 on 2024-05-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required for authentication. Email is unique', max_length=254, unique=True, verbose_name='Email address')),
                ('username', models.CharField(blank=True, help_text='150 characters or fewer.', max_length=150, verbose_name='Username/Fullname')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('companyname', models.CharField(blank=True, help_text='Required. Add company name when creating business profile', max_length=100, null=True, verbose_name='Company name')),
                ('companyemail', models.EmailField(blank=True, help_text='Required. Add company email address when creating business profile.This email address is not unique.', max_length=254, null=True, verbose_name='Company Email address')),
                ('phonenumber', models.CharField(blank=True, help_text='Required. Add company phone number when creating business profile.', max_length=15, null=True, verbose_name='Company Phone number')),
                ('companyaddress', models.TextField(blank=True, help_text='Required. Add company address when creating business profile.', null=True, verbose_name='Company address')),
                ('otp', models.CharField(blank=True, help_text='This field stores the OTP and will reset once authenticated.', max_length=7, null=True, verbose_name='OTP')),
                ('user_email_verified', models.BooleanField(default=False, help_text="False by default, True when user's email is verified", verbose_name='User Verified')),
                ('business_email_verified', models.BooleanField(default=False, help_text='False by default, True when business email is verified', verbose_name='Business Verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
