# Generated by Django 5.0.6 on 2024-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_is_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_adminuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='Adminuser status'),
        ),
    ]
