# Generated by Django 5.0.6 on 2024-05-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialconnect', '0004_rename_instagramaccounts_instagramaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='instagram_username',
            new_name='username',
        ),
    ]
