# Generated by Django 5.0.6 on 2024-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialconnect', '0006_alter_socialhandle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaRevokePremission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=100)),
                ('revoke_url', models.URLField()),
            ],
        ),
    ]
