# Generated by Django 5.0.6 on 2024-07-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialconnect', '0007_socialmediarevokepremission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediarevokepremission',
            old_name='social_media_name',
            new_name='provider',
        ),
    ]
